#!/usr/bin/env python

import os
import subprocess
import shutil
import stat
import platform
import argparse

from StringIO import StringIO
from zipfile import ZipFile
from urllib import urlopen

REQUIREMENTS = [ "pip", "git" ]

FILES_IGNORED_FOR_DELETION = [ "google_appengine" ]

PROJECT_DIR = os.path.abspath(os.path.dirname(__file__))
REQUIREMENTS_FILE = os.path.join(PROJECT_DIR, "requirements.txt")
TARGET_DIR = os.path.join(PROJECT_DIR, "sitepackages")

APPENGINE_TARGET_DIR = os.path.join(TARGET_DIR, "google_appengine")

APPENGINE_SDK_VERSION = "1.9.40"
APPENGINE_SDK_FILENAME = "google_appengine_%s.zip" % APPENGINE_SDK_VERSION

# Google move versions from 'featured' to 'deprecated' when they bring out new releases
FEATURED_SDK_REPO = "https://storage.googleapis.com/appengine-sdks/featured/"
DEPRECATED_SDK_REPO = "https://storage.googleapis.com/appengine-sdks/deprecated/%s/" % APPENGINE_SDK_VERSION.replace('.', '')


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description='Install wagaetail dependencies into local sitepackages/ directory along with the '
                    'Google AppEngine SDK.'
    )
    parser.add_argument(
        '--wagae-develop',
        action='store_true',
        help='Setup for wagaetail development. Installs a symlink in sitepackages/ to where wagtail is currently '
             'installed in the currently active virtualenv. Assumes wagaetail was installed via setuptools in '
             '\'develop\' mode.'
    )
    command_args = parser.parse_args()

    # Make sure the user has everything they need
    where = 'which'
    if platform.system() == 'Windows':
        where = 'where'

    for command in REQUIREMENTS:
        try:
            subprocess.check_output([where, command])
        except subprocess.CalledProcessError:
            raise RuntimeError("You must install the '%s' command" % command)

    if not os.path.exists(TARGET_DIR):
        print('Creating `sitepackages` directory for dependencies...')
        os.makedirs(TARGET_DIR)

    if not os.path.exists(APPENGINE_TARGET_DIR):
        print('Downloading the AppEngine SDK...')

        # First try and get it from the 'featured' folder
        sdk_file = urlopen(FEATURED_SDK_REPO + APPENGINE_SDK_FILENAME)
        if sdk_file.getcode() == 404:
            #Failing that, 'deprecated'
            sdk_file = urlopen(DEPRECATED_SDK_REPO + APPENGINE_SDK_FILENAME)

        # Handle other errors
        if sdk_file.getcode() >= 299:
            raise Exception('App Engine SDK could not be found. {} returned code {}.'.format(
                sdk_file.geturl(), sdk_file.getcode()))

        zipfile = ZipFile(StringIO(sdk_file.read()))
        zipfile.extractall(TARGET_DIR)

        # Make sure the dev_appserver and appcfg are executable
        for module in ("dev_appserver.py", "appcfg.py"):
            app = os.path.join(APPENGINE_TARGET_DIR, module)
            st = os.stat(app)
            os.chmod(app, st.st_mode | stat.S_IEXEC)
    else:
        print('Not updating SDK as it exists. Remove {} and re-run to get the latest SDK'.format(APPENGINE_TARGET_DIR))

    # Remove develop symlink (if it exists) before running pip
    wagaetail_sitepackages_dir = os.path.join(TARGET_DIR, 'wagtail')
    if (command_args.wagae_develop and
            os.path.isdir(wagaetail_sitepackages_dir) and os.path.islink(wagaetail_sitepackages_dir)):
        os.rmdir(wagaetail_sitepackages_dir)

    # Remove all folders and files, we leave symlinks as they will be pointing to submodules
    filenames = (filename for filename in os.listdir(TARGET_DIR) if filename not in FILES_IGNORED_FOR_DELETION)
    for filename in filenames:
        path = os.path.join(TARGET_DIR, filename)
        if os.path.isdir(path) and not os.path.islink(path):
            shutil.rmtree(path)
        elif os.path.isfile(path):
            os.remove(path)

    print("Running pip...")
    args = ["pip", "install", "-r", REQUIREMENTS_FILE, "-t", TARGET_DIR, "-I"]
    p = subprocess.Popen(args)
    p.wait()

    # If develop mode, install symlink to checked out wagaetail project in sitepackages/
    if command_args.wagae_develop:
        # Check wagaetail is installed and import module
        try:
            wagaetail = __import__('wagtail')
        except ImportError:
            raise Exception("wagaetail not installed. Have you installed wagaetail into your virtualenv via "
                            "`setup.py develop`?")

        # Get path to wagaetail module project dir
        wagaetail_project_dir = os.path.dirname(wagaetail.__file__)

        # Remove wagaetail distribution installed via pip above
        shutil.rmtree(wagaetail_sitepackages_dir)

        # Create symbolic link to wagaetail
        os.symlink(wagaetail_project_dir, wagaetail_sitepackages_dir)

        print("[wagae-develop mode] Symbolic link created at {} to {}".format(
            wagaetail_sitepackages_dir,
            wagaetail_project_dir)
        )
